version: '3.1'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./moodle:/var/www/html/
      - ./moodle_data:/var/moodledata
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile-mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: moodlepassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  moodledata:
    driver: local
  db_data: