version: '3'
services:
  mariadb:
    image: 'mariadb:10'
    container_name: db
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_DATABASE: moodle
      MARIADB_USER: root
      MARIADB_PASSWORD: ''
    volumes:
      - $HOME/volumes/mysql:/var/lib/mysql

  moodle:
    image: 'bitnami/moodle:3'
    container_name: moodle
    environment:
      MOODLE_USERNAME: flvlaur
      MOODLE_PASSWORD: Test123!
      MOODLE_EMAIL: flaviuslaurentiu26@yahoo.com
      MOODLE_DATABASE_HOST: db
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_USER: root
      MOODLE_DATABASE_NAME: moodle
      MOODLE_DATABASE_PASSWORD: ''
      ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - $HOME/volumes/moodle:/bitnami
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
